main:
  push:
    - name: sync-github
      stages:
        - name: 同步 Github 仓库
          imports:
            - https://cnb.cool/hin/env/-/blob/main/cnb2github.yml
          script: |
            git remote add github https://x-access-token:$GITHUB_TOKEN@github.com/W4J1e/memox_web
            git push github main --force